# Generated by Django 5.2.8 on 2026-03-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('abstract', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('authors', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(choices=[('pubmed', 'PubMed'), ('arxiv', 'arXiv')], max_length=20)),
                ('published_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancer_type', models.CharField(blank=True, default='unknown', max_length=255)),
                ('ai_method', models.CharField(blank=True, default='unknown', max_length=255)),
                ('embedding_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
